title: Caporaso Lab
description: >
  The Caporaso Lab at Northern Arizona University. We focus on bioinformatics
  software development, and applying bioinformatics to study the human
  microbiome.

baseurl: "/nau" # the subpath of your site, e.g. /blog/
url: "https://cap-lab.bio" # the base hostname & protocol for your site

author:
  fullname: Cap Lab
  github: caporaso-lab
  youtube: qiime2

# Build settings
markdown: kramdown
